### ISSUE TITLE
Issue with stats.sh not being persistent

### ISSUE THREAD

**Issue by grctest** [grctest/GRC-Netdata#4]
The GRC graphs on netdata rely on the script stats.sh, this script is called with the following command:
"source ./stats.sh >/dev/null 2>&1 < /dev/null &"

After a few hours, the stats.sh script fails and it looks like the GRC client is dead to netdata.

Need to figure out how to make the stats.sh script more persistent!

Perhaps related to the [timing issue](https://github.com/grctest/GRC-Netdata/issues/3)?

**Comment by NickAnEngineer** [comment]
I think this is solved if you use the service I pushed a few days ago #8
